// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyb56wPUscPIhGnGsPcqZXlI0zEOBFfY8',
    appId: '1:963687368711:web:d71cb045e3b712d1b582a2',
    messagingSenderId: '963687368711',
    projectId: 'ic-lsg-app',
    authDomain: 'ic-lsg-app.firebaseapp.com',
    storageBucket: 'ic-lsg-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxTGz5dREAI-mXGyc2bsEGS4UKOU0Fto',
    appId: '1:963687368711:android:8b31ec40683f51deb582a2',
    messagingSenderId: '963687368711',
    projectId: 'ic-lsg-app',
    storageBucket: 'ic-lsg-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUbioKB1YMbWNzEgaQR7BYbDvToURPyiw',
    appId: '1:963687368711:ios:4bcc4556c0df9129b582a2',
    messagingSenderId: '963687368711',
    projectId: 'ic-lsg-app',
    storageBucket: 'ic-lsg-app.firebasestorage.app',
    iosBundleId: 'com.example.icsaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUbioKB1YMbWNzEgaQR7BYbDvToURPyiw',
    appId: '1:963687368711:ios:4bcc4556c0df9129b582a2',
    messagingSenderId: '963687368711',
    projectId: 'ic-lsg-app',
    storageBucket: 'ic-lsg-app.firebasestorage.app',
    iosBundleId: 'com.example.icsaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyb56wPUscPIhGnGsPcqZXlI0zEOBFfY8',
    appId: '1:963687368711:web:3f15a63dbb85717cb582a2',
    messagingSenderId: '963687368711',
    projectId: 'ic-lsg-app',
    authDomain: 'ic-lsg-app.firebaseapp.com',
    storageBucket: 'ic-lsg-app.firebasestorage.app',
  );

}