// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvh-TEITkzOHiE10ar5SfHgmVc-qsJqUY',
    appId: '1:600698365943:web:f3c002fb5ba2e3d61e30f2',
    messagingSenderId: '600698365943',
    projectId: 'icsa-microservices',
    authDomain: 'icsa-microservices.firebaseapp.com',
    storageBucket: 'icsa-microservices.firebasestorage.app',
    measurementId: 'G-D5K0XTC38M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbWpX5Zz_SB5YJkrDAYycuzvlGYDLopA',
    appId: '1:600698365943:android:939fd7bbc7deac611e30f2',
    messagingSenderId: '600698365943',
    projectId: 'icsa-microservices',
    storageBucket: 'icsa-microservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZUGL4GL2ytZf4Pvr_nmiv8WPi4mrh-aI',
    appId: '1:600698365943:ios:5442311bbc0ede4b1e30f2',
    messagingSenderId: '600698365943',
    projectId: 'icsa-microservices',
    storageBucket: 'icsa-microservices.firebasestorage.app',
    iosBundleId: 'com.example.icsaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZUGL4GL2ytZf4Pvr_nmiv8WPi4mrh-aI',
    appId: '1:600698365943:ios:5442311bbc0ede4b1e30f2',
    messagingSenderId: '600698365943',
    projectId: 'icsa-microservices',
    storageBucket: 'icsa-microservices.firebasestorage.app',
    iosBundleId: 'com.example.icsaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvh-TEITkzOHiE10ar5SfHgmVc-qsJqUY',
    appId: '1:600698365943:web:ab4324b53535cefd1e30f2',
    messagingSenderId: '600698365943',
    projectId: 'icsa-microservices',
    authDomain: 'icsa-microservices.firebaseapp.com',
    storageBucket: 'icsa-microservices.firebasestorage.app',
    measurementId: 'G-CX5CK0EBP2',
  );
}
